/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package from;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.util.calendar.BaseCalendar;



/**
 *
 * @author Agi Alif
 */
public class frmRetal extends javax.swing.JFrame {
private Connection con;
private Statement st;
private ResultSet RsRental;
private ResultSet RsMobil;
private ResultSet RsPenyewa;
private String sql="";
private String idrental,nama_mobil,idmobil,nama_penyewa,idpenyewa,status,statusb,tanggal,merek,tgl2;
private int harga,hari,total,driver=50000,total1;
    /**
     * Creates new form frmRetal
     */
    public frmRetal() {
        initComponents();
        KoneksiRental();
        TampilData(sql);
    }
    
    private void KoneksiRental(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_rental","root","");
            System.out.println("Koneksi Berhasil");
        }catch (Exception e){
            System.out.println("Koneksi Gagal \n"+e.getMessage());
        }
    }private void TampilData(String sql){
        DefaultTableModel datalist = new DefaultTableModel();
        datalist.addColumn("NO");
        datalist.addColumn("ID RENTAL");
        datalist.addColumn("ID MOBIL");
        datalist.addColumn("ID PENYEWA");
        datalist.addColumn("TANGGAL");
        datalist.addColumn("PENGEMBALIAN");
        datalist.addColumn("HARGA RENTAL");
        datalist.addColumn("STATUS");
        try{
            int i=1;
            st=con.createStatement();
            RsRental=st.executeQuery("select * from tb_rental");
            while (RsRental.next())
                datalist.addRow(new Object[]{
                    (""+i++),
                    RsRental.getString(1),RsRental.getString(5),
                    RsRental.getString(4),RsRental.getString(7),
                    RsRental.getString(8),
                    RsRental.getString(6),RsRental.getString(10)
                });
            TABEL.setModel(datalist);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Tampil \n"+e.getMessage());
        }
    }
    private void bersih(){
        Txt_id_rntl.setText("");
        Cmb_id.setSelectedItem("PILIH");
        Txt_nama.setText("");
        Cmb_id_mobil.setSelectedItem("PILIH");
        Txt_nama_mobil.setText("");
        Txt_merek_mobil.setText("");
        Txt_harga_rental.setText("");
        Cmb_sewa.setSelectedItem("PILIH");
        Cmb_sewa.setSelectedItem("PILIH");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Txt_id_rntl = new javax.swing.JTextField();
        Txt_nama = new javax.swing.JTextField();
        Cmb_id = new javax.swing.JComboBox();
        Cmb_id_mobil = new javax.swing.JComboBox();
        Txt_nama_mobil = new javax.swing.JTextField();
        Txt_merek_mobil = new javax.swing.JTextField();
        Txt_harga_rental = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABEL = new javax.swing.JTable();
        BTN_SAVE = new javax.swing.JButton();
        BTN_EDIT = new javax.swing.JButton();
        BTN_CANCEL = new javax.swing.JButton();
        BTN_DELETE = new javax.swing.JButton();
        Cmb_sewa = new javax.swing.JComboBox();
        Txt_status = new javax.swing.JTextField();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        BTN_HOME = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        DC_kembali1 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        Txt_lama = new javax.swing.JTextField();
        Txt_total = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        CMB_tambahan = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Txt_biaya_rental = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(915, 516));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID RENTAL");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID PENYEWA");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID MOBIL");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MEREK MOBIL");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NAMA PENYEWA");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("HARGA RENTAL");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NAMA MOBIL");

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TANGGAL RENTAL");

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("STATUS");

        Txt_id_rntl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_id_rntlActionPerformed(evt);
            }
        });
        Txt_id_rntl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_id_rntlKeyPressed(evt);
            }
        });

        Txt_nama.setEnabled(false);

        Cmb_id.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cmb_idItemStateChanged(evt);
            }
        });
        Cmb_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_idActionPerformed(evt);
            }
        });

        Cmb_id_mobil.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cmb_id_mobilItemStateChanged(evt);
            }
        });
        Cmb_id_mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_id_mobilActionPerformed(evt);
            }
        });

        Txt_nama_mobil.setEnabled(false);

        Txt_merek_mobil.setEnabled(false);
        Txt_merek_mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_merek_mobilActionPerformed(evt);
            }
        });

        Txt_harga_rental.setEnabled(false);
        Txt_harga_rental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_harga_rentalActionPerformed(evt);
            }
        });

        TABEL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID RENTAL", "ID PENYEWA", "NAMA MOBIL", "HARGA RENTAL", "TANGGAL", "STATUS"
            }
        ));
        jScrollPane2.setViewportView(TABEL);

        BTN_SAVE.setText("SAVE");
        BTN_SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SAVEActionPerformed(evt);
            }
        });

        BTN_EDIT.setText("EDIT");
        BTN_EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_EDITActionPerformed(evt);
            }
        });

        BTN_CANCEL.setText("CANCEL");

        BTN_DELETE.setText("DELETE");
        BTN_DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DELETEActionPerformed(evt);
            }
        });

        Cmb_sewa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PILIH", "SEWA", " " }));
        Cmb_sewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_sewaActionPerformed(evt);
            }
        });

        Txt_status.setEnabled(false);

        dateChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateChooserPropertyChange(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TRANSAKSI");

        BTN_HOME.setText("HOME");
        BTN_HOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_HOMEActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Rp.");

        DC_kembali1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DC_kembali1PropertyChange(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SAMPAI");

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("LAMA PEMINJAMAN");

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("TOTAL HARGA");

        CMB_tambahan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PILIH", "DRIVER" }));
        CMB_tambahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMB_tambahanActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("TAMBAHAN");

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("HARI");

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("BIAYA RENTAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(BTN_SAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(BTN_EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(BTN_CANCEL))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                    .addGap(49, 49, 49))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(81, 81, 81)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_harga_rental, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cmb_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_merek_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_nama_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_id_rntl, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cmb_id_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cmb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BTN_DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addComponent(BTN_HOME, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(149, 149, 149))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Txt_total)
                                        .addComponent(CMB_tambahan, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DC_kembali1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Txt_lama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17))
                                    .addComponent(Txt_biaya_rental, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(154, 154, 154))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Cmb_sewa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Txt_id_rntl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Cmb_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cmb_id_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_nama_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_merek_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_harga_rental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addGap(5, 5, 5)
                                .addComponent(DC_kembali1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Txt_lama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel17)))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_biaya_rental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CMB_tambahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(53, 53, 53)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_SAVE)
                    .addComponent(BTN_EDIT)
                    .addComponent(BTN_CANCEL)
                    .addComponent(BTN_DELETE)
                    .addComponent(BTN_HOME))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_HOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_HOMEActionPerformed
        main_menu m=new main_menu();
        m.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_HOMEActionPerformed

    private void dateChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChooserPropertyChange
        if(dateChooser.getDate()!=null){
            SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
            tanggal=format.format(dateChooser.getDate());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_dateChooserPropertyChange

    private void Cmb_sewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_sewaActionPerformed
        if(Cmb_sewa.getSelectedItem()=="SEWA"){
            status=String.valueOf(Cmb_sewa.getSelectedItem());
            statusb=String.valueOf(Txt_status.getText());
            statusb="READY";
            Txt_status.setText(String.valueOf(statusb));
        }
        Txt_status.setText(String.valueOf(statusb));
        if(Cmb_sewa.getSelectedItem()=="SEWA"){
            Cmb_id_mobil.removeAllItems();
            Cmb_id_mobil.addItem("PILIH");
            try{
                status=String.valueOf(Cmb_sewa.getSelectedItem());
                status="READY";
                String sql = "select * from tb_mobil where status ='"+status+"'";
                Statement st = con.createStatement();
                RsMobil=st.executeQuery(sql);
                while (RsMobil.next()){
                    String Aliaskd = RsMobil.getString("nama_mobil");
                    Cmb_id_mobil.addItem(Aliaskd);
                }
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Gagal Menampilkan Nama Mobil \n"+e.getMessage());
            }
            Cmb_id.removeAllItems();
            Cmb_id.addItem("PILIH");
            try{
                status=String.valueOf(Cmb_sewa.getSelectedItem());
                status="READY";
                String sql = "select * from tb_penyewa where status = '"+status+"'";
                Statement st = con.createStatement();
                RsPenyewa=st.executeQuery(sql);
                while (RsPenyewa.next()){
                    String Aliaskd = RsPenyewa.getString("id_penyewa");
                    Cmb_id.addItem(Aliaskd);
                }
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Gagal Menampilkan Nama mobil \n"+e.getMessage());
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmb_sewaActionPerformed

    private void BTN_DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DELETEActionPerformed
        idrental=String.valueOf(Txt_id_rntl.getText());
        try{
            sql="delete from tb_rental where id_rental = '"+idrental+"'";
            st=con.createStatement();
            st.execute(sql);
            bersih();
            TampilData(sql);
            JOptionPane.showMessageDialog(null, "Data Terhapus");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error"+e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_DELETEActionPerformed

    private void BTN_EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EDITActionPerformed
        idrental=String.valueOf(Txt_id_rntl.getText());
        nama_mobil=String.valueOf(Cmb_id_mobil.getSelectedItem());
        idpenyewa=String.valueOf(Cmb_id.getSelectedItem());
        nama_penyewa=String.valueOf(Txt_nama.getText());
        harga=Integer.parseInt(Txt_harga_rental.getText());
        status=String.valueOf(Txt_status.getText());
        try{
            sql="update tb_rental set nama_mobil='"+nama_mobil+"',id_penyewa = '"+idpenyewa+"',nama_penyewa='"+nama_penyewa+"',nama_mobil='"+nama_mobil+"',tgl_rental='"+tanggal+"',rental='"+harga+"',status='"+status+"',where id_rental='"+idrental+"'";
            st=con.createStatement();
            st.execute(sql);
            bersih();
            TampilData(sql);
            JOptionPane.showMessageDialog(null, "Data Sudah Di Update");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Data Gagal Di Update"+e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_EDITActionPerformed

    private void BTN_SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SAVEActionPerformed
        idrental=String.valueOf(Txt_id_rntl.getText());
        nama_mobil=Cmb_id_mobil.getItemAt(Cmb_id_mobil.getSelectedIndex()).toString();
        idpenyewa=Cmb_id.getItemAt(Cmb_id.getSelectedIndex()).toString();
        nama_penyewa=String.valueOf(Txt_nama.getText());
        idmobil=String.valueOf(Txt_nama_mobil.getText());
        harga=Integer.parseInt(Txt_harga_rental.getText());
        status=Cmb_sewa.getItemAt(Cmb_sewa.getSelectedIndex()).toString();
        if(Cmb_sewa.getSelectedItem().equals("PILIH")){
            JOptionPane.showMessageDialog(null, "STATUS BELUM DIPILIH");
        }else {
            try{
                sql="insert into tb_rental(id_rental,id_mobil,id_penyewa,nama_penyewa,nama_mobil,tgl_rental,harga_rental,tgl_kembali,total,status)value"
                + "('"+idrental+"','"+idmobil+"','"+idpenyewa+"','"+nama_penyewa+"','"+nama_mobil+"','"+tanggal+"','"+harga+"','"+tgl2+"','"+total1+"','"+status+"')";
                st=con.createStatement();
                st.execute(sql);
                bersih();
                TampilData(sql);
                JOptionPane.showMessageDialog(null,"DATA TERSIMPAN");
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "DATA GAGAL DISIMPAN \n"+e.getMessage());
            }
        }
        try{
            status="SUDAH MENYEWA";
            sql="update tb_mobil set status = '"+status+"' where nama_mobil= '"+nama_mobil+"'";
            st=con.createStatement();
            st.executeUpdate(sql);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "maaf error"+e.getMessage());
        }
        try{
            String sql="select * from tb_penyewa";
            Statement st=con.createStatement();
            RsPenyewa=st.executeQuery(sql);
            status="SUDAH MENYEWA";
            sql="update tb_penyewa set status = '"+status+"' where id_penyewa = '"+idpenyewa+"'";
            st=con.createStatement();
            st.executeUpdate(sql);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "maaf Error"+e.getMessage());
        }

    }//GEN-LAST:event_BTN_SAVEActionPerformed

    private void Txt_harga_rentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_harga_rentalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_harga_rentalActionPerformed

    private void Txt_merek_mobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_merek_mobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_merek_mobilActionPerformed

    private void Cmb_id_mobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_id_mobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmb_id_mobilActionPerformed

    private void Cmb_id_mobilItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cmb_id_mobilItemStateChanged
        try{
            sql="select * from tb_mobil where nama_mobil='"+Cmb_id_mobil.getSelectedItem()+"'";
            st=con.createStatement();
            RsMobil=st.executeQuery(sql);
            while(RsMobil.next()){
                Txt_nama_mobil.setText(RsMobil.getString("id_mobil"));
                Txt_merek_mobil.setText(RsMobil.getString(3));
                Txt_harga_rental.setText(RsMobil.getString(4));
                Cmb_id_mobil.setSelectedItem(RsMobil.getString(5));
            }
            Txt_nama_mobil.requestFocus();
        }catch (Exception e){

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmb_id_mobilItemStateChanged

    private void Cmb_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmb_idActionPerformed

    private void Cmb_idItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cmb_idItemStateChanged
        try{
            sql="select * from tb_penyewa where id_penyewa='"+Cmb_id.getSelectedItem() +"'";
            st=con.createStatement();
            RsPenyewa=st.executeQuery(sql);
            while(RsPenyewa.next()){
                Txt_nama.setText(RsPenyewa.getString("nama_penyewa"));
            }
            Txt_nama.requestFocus();
        }catch(Exception e){

        }
    }//GEN-LAST:event_Cmb_idItemStateChanged

    private void Txt_id_rntlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_id_rntlKeyPressed
        idrental=Txt_id_rntl.getText();
        int pressEnter=evt.getKeyCode();
        if(pressEnter==10){
            try{
                Cmb_id_mobil.removeAllItems();
                String Sql = "select * from tb_mobil";
                Statement st=con.createStatement();
                RsMobil=st.executeQuery(sql);
                while (RsMobil.next()){
                    String Aliaskd = RsMobil.getString("nama_mobil");
                    Cmb_id_mobil.addItem(Aliaskd);
                    Cmb_sewa.setEnabled(false);
                }
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Error"+e.getMessage());
            }
            try{
                Cmb_id.removeAllItems();
                String Sql="select * from tb_penyewa";
                Statement st=con.createStatement();
                RsPenyewa=st.executeQuery(sql);
                while (RsPenyewa.next()){
                    String Aliaskd = RsPenyewa.getString("id_penyewa");
                    Cmb_id.addItem(Aliaskd);
                    Cmb_sewa.setEnabled(false);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"ERROR"+e.getMessage());
            }
        }   try{
            sql="select * from tb_rental where id_rental='"+idrental+"'";
            st=con.createStatement();
            RsRental=st.executeQuery(sql);
            while (RsRental.next()){
                Cmb_id.setSelectedItem(RsRental.getString("id_penyewa"));
                Cmb_id_mobil.setSelectedItem(RsRental.getString("nama_mobil"));
                Txt_nama.setText(RsRental.getString("nama_penyewa"));
                Txt_nama_mobil.setText(RsRental.getString("id_mobil"));
                Txt_harga_rental.setText(RsRental.getString("harga_rental"));
                Txt_status.setText(RsRental.getString("status"));
                dateChooser.setDate(RsRental.getDate("tgl_rental"));
                JOptionPane.showMessageDialog(null, "Data DItemukan");
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Tidak Ada"+e.getMessage());
            Cmb_id_mobil.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_id_rntlKeyPressed

    private void Txt_id_rntlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_id_rntlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_id_rntlActionPerformed

    private void DC_kembali1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DC_kembali1PropertyChange
     if(DC_kembali1.getDate()!=null){
            SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
            tgl2=format.format(DC_kembali1.getDate());
        }
        try{
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            Date pinjam = dateChooser.getDate();
            Date kembali_a = DC_kembali1.getDate();
            long pinjam1 = pinjam.getTime();
            long kembali_b = kembali_a.getTime();
            long diff = kembali_b-pinjam1;
            long lama = diff/(24*60*60*1000);
            Txt_lama.setText(Long.toString(lama));
            harga=Integer.parseInt(Txt_harga_rental.getText());
            hari=Integer.parseInt(Txt_lama.getText());
            total=harga*hari;
            
            Txt_biaya_rental.setText(String.valueOf(total));
           
            
        }catch (Exception e){

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_DC_kembali1PropertyChange

    private void CMB_tambahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMB_tambahanActionPerformed
    try{
        if(CMB_tambahan.getSelectedItem()=="DRIVER"){
        total=Integer.parseInt(Txt_biaya_rental.getText());
        total1=total+driver;
        Txt_total.setText(String.valueOf(total1));
        
    }else if(CMB_tambahan.getSelectedItem()=="PILIH")
    {
        total=Integer.parseInt(Txt_biaya_rental.getText());
        total1=total;
        Txt_total.setText(String.valueOf(total));
    }
    }catch(Exception e){
    }  // TODO add your handling code here:
    }//GEN-LAST:event_CMB_tambahanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRetal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRetal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRetal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRetal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRetal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_CANCEL;
    private javax.swing.JButton BTN_DELETE;
    private javax.swing.JButton BTN_EDIT;
    private javax.swing.JButton BTN_HOME;
    private javax.swing.JButton BTN_SAVE;
    private javax.swing.JComboBox CMB_tambahan;
    private javax.swing.JComboBox Cmb_id;
    private javax.swing.JComboBox Cmb_id_mobil;
    private javax.swing.JComboBox Cmb_sewa;
    private com.toedter.calendar.JDateChooser DC_kembali1;
    private javax.swing.JTable TABEL;
    private javax.swing.JTextField Txt_biaya_rental;
    private javax.swing.JTextField Txt_harga_rental;
    private javax.swing.JTextField Txt_id_rntl;
    private javax.swing.JTextField Txt_lama;
    private javax.swing.JTextField Txt_merek_mobil;
    private javax.swing.JTextField Txt_nama;
    private javax.swing.JTextField Txt_nama_mobil;
    private javax.swing.JTextField Txt_status;
    private javax.swing.JTextField Txt_total;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
